import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>crIAte</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon/dark.svg" type="image/svg+xml" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#15162c] to-[#040209]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-accent">crIAte</span>
          </h1>
          <p className="text-2xl font-bold">
            Tu asistente para la creación posts y anuncios sobre tu producto.
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
